[package]
name = "xtream"
version = "0.1.0"
edition = "2024"
description = "Xtream Codes API client (native + wasm)"

[dependencies]
idna_adapter = "=1.0.0"
futures-core = "0.3"
reqwest = { version = "0.13.5", features = ["stream"], default-features = false }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = { version = "1.0.151", features = ["raw_value"] }
thiserror = "2.0.21"

[dev-dependencies]
reqwest = { version = "0.13.5", features = ["rustls"] }
tokio = { version = "1.53.1", features = ["macros", "rt"] }
